name: Deploy data-server  server prod

on:
  push:
    branches: ['master']
  workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to run the workflow on'
          required: true
          type: string
          default: 'master'

env:
  KEY: sit  # 全局定义 KEY 环境变量
  ECR_REGISTRY: 147997140725.dkr.ecr.ap-southeast-1.amazonaws.com  # 全局定义 ECR_REGISTRY
  ECR_REPOSITORY: sit/bitbot/rsshub  # 全局定义 ECR_REPOSITORY
  IMAGE_TAG: rsshub-${{ github.sha }}-${{ github.event.repository.updated_at}}  # 全局定义 IMAGE_TAG

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2



      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-eks:
    needs: [build-and-push]
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install kubectl
        run: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x kubectl
            sudo mv kubectl /usr/local/bin/kubectl

      - name: Configure AWS CLI for EKS
        run: |
             aws eks --region ap-southeast-1 update-kubeconfig --name bitbot-${{ env.KEY }}-eks

      - name: Update eks
        run: |
          kubectl -n sit set image deployment/rsshub rsshub=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG



