name: Deploy data-server server prod

on:
  push:
    branches: ['master']
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        type: string
        default: 'master'

env:
  KEY: sit  # 全局定义 KEY 环境变量
  ECR_REGISTRY: 147997140725.dkr.ecr.ap-southeast-1.amazonaws.com  # 全局定义 ECR_REGISTRY
  ECR_REPOSITORY: sit/bitbot/rsshub  # 全局定义 ECR_REPOSITORY

jobs:
  generate-tag:
    name: Generate Image Tag
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.generate-tag.outputs.image_tag }}

    steps:
      - name: Generate timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date -u +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Generate IMAGE_TAG
        id: generate-tag
        run: |
          IMAGE_TAG="rsshub-${{ github.sha }}-${{ env.TIMESTAMP }}"
          echo "Generated IMAGE_TAG: ${IMAGE_TAG}"  # 打印生成的 IMAGE_TAG
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    needs: generate-tag  # 添加对 generate-tag 作业的依赖
    environment: production

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ needs.generate-tag.outputs.image_tag }}  # 使用 generate-tag 作业的输出
        run: |
          echo "Using IMAGE_TAG: ${IMAGE_TAG}"  # 打印使用的 IMAGE_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy-to-eks:
    needs: [generate-tag, build-and-push]  # 添加对 generate-tag 和 build-and-push 作业的依赖
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOY_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEPLOY_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl

      - name: Configure AWS CLI for EKS
        run: |
          aws eks --region ap-southeast-1 update-kubeconfig --name bitbot-${{ env.KEY }}-eks

      - name: Update eks
        env:
          IMAGE_TAG: ${{ needs.generate-tag.outputs.image_tag }}  # 使用 generate-tag 作业的输出
        run: |
          kubectl -n prod set image deployment/rsshub rsshub=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
